### ISSUE TITLE
Pos of data node is None for trailing newline

### ISSUE THREAD

**Issue by Evan-Zhao** [phfaist/pylatexenc#34] opened 2020-03-27 18:11 UTC
Hello devs,

When I was using `LatexWalker` on a string with trailing newline after an environment, that newline is parsed into a `LatexCharsNode` with `pos = None`. Is this intentional?

I'm using version 2.1 (installed from pip); a minimal input that displays this behavior would be "\\begin{table}\n\\end{table}\n".

Also, thanks for the great work! I'm writing a customary latex formatter and this library really helps!

**Comment by phfaist** [comment] 2020-04-20 10:11
Thanks for your feedback! I tested this with the latest git master and I can't reproduce the bug. It might be because I did change some minor things in how nodes are parsed specially towards the end of the input, so this hopefully also fixed your bug. I'm closing this issue for now, but please do feel free to re-open if you find the bug is still there.

**Closed by phfaist** 2020-04-20 10:11 UTC
