### ISSUE TITLE
LatexNodes2Text removes whitespace between neighboring braced groups

### ISSUE THREAD

**Issue by iburago** [phfaist/pylatexenc#28] opened 2019-11-09 23:30 UTC
When converting LaTeX to plain text, the conversion methods of the
`LatexNodes2Text` class consume whitespace between neighboring
braced groups in the `strict_latex_spaces=True` mode, deviating from
the LaTeX handling of whitespace in such cases.

For instance, `LatexNodes2Text().latex_to_text('{a} {b}')` returns
`ab` instead of `a b`.

**Comment by phfaist** [comment] 2019-11-15 14:15
Hi, thanks for your feedback. I can't reproduce your bug with `pylatexenc 2.1` if I specify `strict_latex_spaces=True`:
```
>>> from pylatexenc.latex2text import LatexNodes2Text
>>> LatexNodes2Text(strict_latex_spaces=True).latex_to_text('{a} {b}')
'a b'
>>> LatexNodes2Text().latex_to_text('{a} {b}')
'ab'
```

The reason the spacing is a bit weird by default (if you don't specify the `strict_latex_spaces` argument) is purely historical—and somewhat subjectively aesthetical—but I'm wary of changing the default behavior because you never know what it can break.

I'm closing this issue for now, but feel free to re-open this issue if you find a way to reproduce your bug with `strict_latex_spaces=True`.

**Closed by phfaist** 2019-11-15 14:15 UTC
