### ISSUE TITLE
parse LaTeX, replace $$

### ISSUE THREAD

**Issue by nschloe** [phfaist/pylatexenc#75] opened 2022-02-15 10:20 UTC
I'm thinking about using pylatexenc for [blacktex](https://github.com/nschloe/blacktex). blacktex changes certain common LaTeX anti-patterns, for example it replaces dollar-math `$...$` with `\(...\)` (as recommended [here](https://tex.stackexchange.com/q/510/13262)).

I tried to simply replace the delimiters, but that won't work:
```python
from pylatexenc.latexwalker import LatexWalker, LatexMathNode

def replace_dollar_math(string: str) -> str:
    w = LatexWalker(string)
    nodelist, _, _ = w.get_latex_nodes(pos=0)
    for item in nodelist:
        if isinstance(item, LatexMathNode) and item.delimiters == ("$", "$"):
            item.delimiters = ("\\(", "\\)")

    return "".join([item.latex_verbatim() for item in nodelist])


string = "inline math: $a+b=c$ more text"

print(replace_dollar_math(string))
```
```
inline math: $a+b=c$ more text
```
I'm a bit confused as to what's going wrong here. Any hints?

**Comment by phfaist** [comment] 2022-02-15 13:43
The problem is with the use of `node.latex_verbatim()`. The `latex_verbatim()` method does not recompose the latex code from the node information, but rather, returns the part of the original string that this node represents. I did not provide an official full-featured "recomposed latex" method for the node classes because it might not be reliable, especially in the case of custom macros with custom argument parsing. I've gone some way in this direction in my parallel project [`latexpp`](https://github.com/phfaist/latexpp). There might be code you could reuse there. You can also copy code from [this function](https://github.com/phfaist/pylatexenc/blob/main/pylatexenc/latexwalker/_helpers.py#L63), which is a quick-and-dirty way of recomposing the latex code for a node; it can have some unreliable behavior as mentioned above.

In your case, you could probably do something along the lines of
```python
def replace_dollar_math(string: str) -> str:
    w = LatexWalker(string)
    nodelist, _, _ = w.get_latex_nodes(pos=0)
    return replace_dollar_math_nodelist(nodelist)

def replace_dollar_math_nodelist(nodelist):
    return "".join([replace_dollar_math_node(n) for n in nodelist])

def replace_dollar_math_node(node):
    if isinstance(item, LatexMathNode) and item.delimiters == ("$", "$"):
        return "\\(" + node.nodelist + "\\)"
    # you could either recurse into child nodes (e.g., macro arguments,
    # environment body, etc.) or simply return node.latex_verbatim() if you
    # only want to process root-level math mode content.
    if (node.isNodeType(LatexMacroNode) or node.isNodeType( ... ) ... ):
        return ...
    # return node.latex_verbatim()
```
(I didn't test this code.) But actually it does seem like your goal isn't too far from `latexpp`'s. You might even be able to directly use its API if you like.

I'm closing this issue, feel free to reopen if you think there should be some change in `pylatexenc`'s code base.

**Closed by phfaist** 2022-02-15 13:43 UTC

**Comment by nschloe** [comment] 2022-02-15 14:20
```python
return "\\(" + node.nodelist + "\\)"
```
This is not going to work, is it? You can't concatenate strings with a list.

(Don't have the right to reopen.)

**Comment by nschloe** [comment] 2022-02-15 14:41
Something that _does_ work is
```python
node.delimiters = ("\\(", "\\)")
nodelist_to_latex([node])
```
I think the function `nodelist_to_latex` is very useful and I'd even argue it should be the `__str__` method in `LatexNode`, such that
```
str(node)
```
works. Parsing the LaTeX tree is one (great!) thing, but recreating the original input from the parse is the other half of the trick. :smile_cat:

**Comment by phfaist** [comment] 2022-09-17 15:00
Ah sorry, it should have read `return "\\(" + [n.latex_verbatim() for n in node.nodelist] + "\\)"` although that will also miss some edge cases (such as `$a_{\text{b+$c$}}$`).

The `nodelist_to_latex()` function is archaic and should not be directly used unless you are certain that the node tree you're applying it to is very simple. There is currently no reliable way of recreating latex input from the node structure. This is because pylatexenc offers a lot of flexibility for custom parsers, etc., and does not always keep all the necessary information to recreate the input latex. E.g., comments after a macro name and before arguments are not stored in the node structure and would simply disappear if you used a function along the lines of `nodelist_to_latex`. Round-trip handling of LaTeX nodes is handled in my sister project [latexpp](https://github.com/phfaist/latexpp), which might be useful in your case.
